# Generated by Django 2.0.2 on 2018-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=150)),
                ('stu_mail', models.CharField(max_length=150)),
                ('stu_address', models.CharField(max_length=300)),
                ('stu_mobile', models.IntegerField()),
                ('stu_roll', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
