# Generated by Django 2.0.2 on 2018-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_roll', models.IntegerField()),
                ('stu_semester', models.CharField(default='', max_length=50)),
                ('paid_amount', models.IntegerField(default='0')),
                ('receipt_no', models.CharField(max_length=300)),
                ('remarks', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'payfees',
            },
        ),
    ]
