# Generated by Django 2.0.2 on 2018-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=400)),
                ('notification_attachment_url', models.CharField(max_length=400)),
                ('notification_text', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
