# Generated by Django 2.0.2 on 2018-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_stu_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_mail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_mobile',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_password',
            field=models.CharField(max_length=300),
        ),
    ]
