# Generated by Django 2.0.2 on 2018-02-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180213_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_branch', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stu_branch_id',
            field=models.IntegerField(default='-1'),
        ),
    ]
