# Generated by Django 2.0.2 on 2018-02-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180214_0320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
