# Generated by Django 2.0.2 on 2018-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180214_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_course', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_semester', models.IntegerField()),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='stu_course_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_semester_id',
            field=models.IntegerField(default='-1'),
        ),
    ]
